### ISSUE TITLE
Deprecated selector in `meteor-api\styles\meteor-color-coding.less`

### ISSUE THREAD

**Issue by codedeep** [awatson1978/meteor-api#85] opened 2017-02-16 15:47 UTC
In `meteor-api\styles\meteor-color-coding.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .api.meteor` => `atom-text-editor.editor .syntax--api.syntax--meteor`

* `atom-text-editor::shadow .api.meteor.core` => `atom-text-editor.editor .syntax--api.syntax--meteor.syntax--core`

* `atom-text-editor::shadow .api.meteor.ddp` => `atom-text-editor.editor .syntax--api.syntax--meteor.syntax--ddp`

* `atom-text-editor::shadow .api.meteor.http` => `atom-text-editor.editor .syntax--api.syntax--meteor.syntax--http`

* `atom-text-editor::shadow .api.meteor.template` => `atom-text-editor.editor .syntax--api.syntax--meteor.syntax--template`

* `atom-text-editor::shadow .api.meteor.blaze` => `atom-text-editor.editor .syntax--api.syntax--meteor.syntax--blaze`

* `atom-text-editor::shadow .api.meteor.router` => `atom-text-editor.editor .syntax--api.syntax--meteor.syntax--router`

* `atom-text-editor::shadow .api.meteor.collection` => `atom-text-editor.editor .syntax--api.syntax--meteor.syntax--collection`

* `atom-text-editor::shadow .api.meteor.session` => `atom-text-editor.editor .syntax--api.syntax--meteor.syntax--session`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by franzos** [comment] 2017-03-17 10:30
This is a duplicate of #84 .

**Closed** 2024-09-24 16:23 UTC
